//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Driver={SQLite3 ODBC Driver};database=C:\\Users\\racs_\\Source\\Repos\\Control_Inventa" +
            "rio\\ControlInsumos\\bin\\Debug\\dbinsumos.db;stepapi=0;notxn=0;shortnames=0;longnam" +
            "es=0;nocreat=0;nowchar=0;fksupport=0;oemcp=0;bigint=0;jdconv=0")]
        public string C__Users_racs__Source_Repos_Control_Inventario_ControlInsumos_bin_Debug_dbinsumos_dbConnectionString {
            get {
                return ((string)(this["C__Users_racs__Source_Repos_Control_Inventario_ControlInsumos_bin_Debug_dbinsumos" +
                    "_dbConnectionString"]));
            }
        }
    }
}
